// Generated by CoffeeScript 1.6.3
exports.index = function(req, res) {
  var Course, cheerio, fs, _;
  cheerio = require('cheerio');
  _ = require('underscore');
  Course = require('./../models/course');
  fs = require('fs');
  return fs.readFile('public/xml/syllabus2013.xml', 'utf8', function(err, xml) {
    var $, courses;
    if (err != null) {
      res.writeHead(404, 'Content-Type: text/plain');
      return res.write('not found');
    } else {
      if (_.keys(req.query).length > 0) {
        $ = cheerio.load(xml, {
          ignoreWhitespave: true,
          xmlMode: true
        });
        courses = _.map($(xml).find('Course'), function(course) {
          return new Course($(course));
        });
        courses = _.select(courses, function(course) {
          return course.is(req.query);
        });
        return res.render('list', {
          courses: courses
        });
      } else {
        return res.render('index');
      }
    }
  });
};
