// Generated by CoffeeScript 1.6.3
var Course;

Course = (function() {
  function Course(course) {
    var cheerio, _;
    cheerio = require('cheerio');
    _ = require('underscore');
    this.title = course.find('Title').text();
    this.etitle = course.find('ETitle');
    this.department = course.find('Department').text();
    this.year = course.find('Year').text();
    this.required = course.find('RequiredSelective').text();
    this.divide = course.find('Divide').text();
    this.term = course.find('Term').text();
    this.credit = course.find('Credit').text();
    this.lectures = _.map(course.find('Lecturer'), function(l) {
      var $;
      $ = cheerio.load(l, {
        ignoreWhitespace: true,
        xmlMode: true
      });
      return $(l).text();
    });
    this.failureAbsence = course.find('FailureAbsence').text();
    this.evaluation = course.find('Evaluation').text();
  }

  Course.prototype.isDept = function(dept) {
    return this.eDept() === dept;
  };

  Course.prototype.eDept = function() {
    switch (this.department) {
      case '機械工学科':
        return 'm';
      case '電気情報工学科':
        return 'e';
      case '電気情報工学科 電気電子工学コース':
        return 'e';
      case '電気情報工学科 情報工学コース':
        return 'e';
      case '都市システム工学科':
        return 'c';
      case '建築学科':
        return 'a';
    }
  };

  Course.prototype.eCourse = function() {
    if (this.eDept(this.department) === 'e') {
      switch (this.department) {
        case '電気情報工学科 電気電子工学コース':
          return 'd';
        case '電気情報工学科 情報工学コース':
          return 'j';
        default:
          return null;
      }
    } else {
      return null;
    }
  };

  Course.prototype.is = function(query) {
    var result;
    result = true;
    if (query.year != null) {
      result &= query.year === this.year;
    }
    if (query.department != null) {
      result &= this.isDept(query.department);
    }
    if ((query.course != null) && this.year > 3 && this.eDept() === 'e') {
      result &= query.course === this.eCourse();
    }
    return result;
  };

  return Course;

})();

module.exports = Course;
